# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape: 
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 10s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    target_groups:
      - targets: ['localhost:9090']
        labels:
          instance: 'cluster_coreos_prometheus'
      - targets:
          - 'c01:2379'
          - 'c02:2379'
          - 'c03:2379'
          - 'c04:2379'
          - 'c05:2379'
          - 'c06:2379'
          - 'c07:2379'
          - 'c08:2379'
          - 'c09:2379'
          - 'c10:2379'
          - 'c11:2379'
          - 'c12:2379'
          - 'c13:2379'
          - 'c14:2379'
          - 'c15:2379'
          - 'c16:2379'
          - 'c17:2379'
          - 'c18:2379'
          - 'c19:2379'
          - 'c20:2379'
          - 'c21:2379'
          - 'c22:2379'
          - 'c23:2379'
          - 'c24:2379'
          - 'c25:2379'
          - 'c26:2379'
          - 'c27:2379'
          - 'c28:2379'
          - 'c29:2379'
          - 'c30:2379'
          - 'c31:2379'
          - 'c32:2379'
          - 'c33:2379'
          - 'c34:2379'
          - 'c35:2379'
          - 'c36:2379'
          - 'c37:2379'
          - 'c38:2379'
          - 'c39:2379'
          - 'c40:2379'
          - 'c41:2379'
          - 'c42:2379'
          - 'c43:2379'
          - 'c44:2379'
          - 'c45:2379'
          - 'c46:2379'
          - 'c47:2379'
          - 'c48:2379'
          - 'c49:2379'
          - 'c50:2379'
          - 'c51:2379'
          - 'c52:2379'
          - 'c53:2379'
          - 'c54:2379'
          - 'c55:2379'
          - 'c56:2379'
          - 'c57:2379'
          - 'c58:2379'
          - 'c59:2379'
          - 'c60:2379'
          - 'c61:2379'
          - 'c62:2379'
          - 'c63:2379'
          - 'c64:2379'
          - 'c65:2379'
          - 'c66:2379'
          - 'c67:2379'
          - 'c68:2379'
          - 'c69:2379'
          - 'c70:2379'
          - 'c71:2379'
          - 'c72:2379'
          - 'c73:2379'
          - 'c74:2379'
          - 'c75:2379'
          - 'c76:2379'
          - 'c77:2379'
          - 'c78:2379'
          - 'c79:2379'
        labels:
          job: 'etcd2'
      - targets:
          - 'c01:8087'
          - 'c02:8087'
          - 'c03:8087'
          - 'c04:8087'
          - 'c05:8087'
          - 'c06:8087'
          - 'c07:8087'
          - 'c08:8087'
          - 'c09:8087'
          - 'c10:8087'
          - 'c11:8087'
          - 'c12:8087'
          - 'c13:8087'
          - 'c14:8087'
          - 'c15:8087'
          - 'c16:8087'
          - 'c17:8087'
          - 'c18:8087'
          - 'c19:8087'
          - 'c20:8087'
          - 'c21:8087'
          - 'c22:8087'
          - 'c23:8087'
          - 'c24:8087'
          - 'c25:8087'
          - 'c26:8087'
          - 'c27:8087'
          - 'c28:8087'
          - 'c29:8087'
          - 'c30:8087'
          - 'c31:8087'
          - 'c32:8087'
          - 'c33:8087'
          - 'c34:8087'
          - 'c35:8087'
          - 'c36:8087'
          - 'c37:8087'
          - 'c38:8087'
          - 'c39:8087'
          - 'c40:8087'
          - 'c41:8087'
          - 'c42:8087'
          - 'c43:8087'
          - 'c44:8087'
          - 'c45:8087'
          - 'c46:8087'
          - 'c47:8087'
          - 'c48:8087'
          - 'c49:8087'
          - 'c50:8087'
          - 'c51:8087'
          - 'c52:8087'
          - 'c53:8087'
          - 'c54:8087'
          - 'c55:8087'
          - 'c56:8087'
          - 'c57:8087'
          - 'c58:8087'
          - 'c59:8087'
          - 'c60:8087'
          - 'c61:8087'
          - 'c62:8087'
          - 'c63:8087'
          - 'c64:8087'
          - 'c65:8087'
          - 'c66:8087'
          - 'c67:8087'
          - 'c68:8087'
          - 'c69:8087'
          - 'c70:8087'
          - 'c71:8087'
          - 'c72:8087'
          - 'c73:8087'
          - 'c74:8087'
          - 'c75:8087'
          - 'c76:8087'
          - 'c77:8087'
          - 'c78:8087'
          - 'c79:8087'
        labels:
          job: 'cadvisor'

