# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape: 
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 10s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    target_groups:
      - targets: ['cluster-coreos-prometheus-pushgateway.service.consul:9091']
      - targets: ['localhost:9090']
        labels:
          instance: 'cluster_coreos_prometheus'
      - targets:
          - 'c01.ne.cloud.epfl.ch:2379'
          - 'c02.ne.cloud.epfl.ch:2379'
          - 'c03.ne.cloud.epfl.ch:2379'
          - 'c04.ne.cloud.epfl.ch:2379'
          - 'c05.ne.cloud.epfl.ch:2379'
          - 'c06.ne.cloud.epfl.ch:2379'
          - 'c07.ne.cloud.epfl.ch:2379'
          - 'c08.ne.cloud.epfl.ch:2379'
          - 'c09.ne.cloud.epfl.ch:2379'
          - 'c10.ne.cloud.epfl.ch:2379'
          - 'c11.ne.cloud.epfl.ch:2379'
          - 'c12.ne.cloud.epfl.ch:2379'
          - 'c13.ne.cloud.epfl.ch:2379'
          - 'c14.ne.cloud.epfl.ch:2379'
          - 'c15.ne.cloud.epfl.ch:2379'
          - 'c16.ne.cloud.epfl.ch:2379'
          - 'c17.ne.cloud.epfl.ch:2379'
          - 'c18.ne.cloud.epfl.ch:2379'
          - 'c19.ne.cloud.epfl.ch:2379'
          - 'c20.ne.cloud.epfl.ch:2379'
          - 'c21.ne.cloud.epfl.ch:2379'
          - 'c22.ne.cloud.epfl.ch:2379'
          - 'c23.ne.cloud.epfl.ch:2379'
          - 'c24.ne.cloud.epfl.ch:2379'
          - 'c25.ne.cloud.epfl.ch:2379'
          - 'c26.ne.cloud.epfl.ch:2379'
          - 'c27.ne.cloud.epfl.ch:2379'
          - 'c28.ne.cloud.epfl.ch:2379'
          - 'c29.ne.cloud.epfl.ch:2379'
          - 'c30.ne.cloud.epfl.ch:2379'
          - 'c31.ne.cloud.epfl.ch:2379'
          - 'c32.ne.cloud.epfl.ch:2379'
          - 'c33.ne.cloud.epfl.ch:2379'
          - 'c34.ne.cloud.epfl.ch:2379'
          - 'c35.ne.cloud.epfl.ch:2379'
          - 'c36.ne.cloud.epfl.ch:2379'
          - 'c37.ne.cloud.epfl.ch:2379'
          - 'c38.ne.cloud.epfl.ch:2379'
          - 'c39.ne.cloud.epfl.ch:2379'
          - 'c40.ne.cloud.epfl.ch:2379'
          - 'c41.ne.cloud.epfl.ch:2379'
          - 'c42.ne.cloud.epfl.ch:2379'
          - 'c43.ne.cloud.epfl.ch:2379'
          - 'c44.ne.cloud.epfl.ch:2379'
          - 'c45.ne.cloud.epfl.ch:2379'
          - 'c46.ne.cloud.epfl.ch:2379'
          - 'c47.ne.cloud.epfl.ch:2379'
          - 'c48.ne.cloud.epfl.ch:2379'
          - 'c49.ne.cloud.epfl.ch:2379'
          - 'c50.ne.cloud.epfl.ch:2379'
          - 'c51.ne.cloud.epfl.ch:2379'
          - 'c52.ne.cloud.epfl.ch:2379'
          - 'c53.ne.cloud.epfl.ch:2379'
          - 'c54.ne.cloud.epfl.ch:2379'
          - 'c55.ne.cloud.epfl.ch:2379'
          - 'c56.ne.cloud.epfl.ch:2379'
          - 'c57.ne.cloud.epfl.ch:2379'
          - 'c58.ne.cloud.epfl.ch:2379'
          - 'c59.ne.cloud.epfl.ch:2379'
          - 'c60.ne.cloud.epfl.ch:2379'
          - 'c61.ne.cloud.epfl.ch:2379'
          - 'c62.ne.cloud.epfl.ch:2379'
          - 'c63.ne.cloud.epfl.ch:2379'
          - 'c64.ne.cloud.epfl.ch:2379'
          - 'c65.ne.cloud.epfl.ch:2379'
          - 'c66.ne.cloud.epfl.ch:2379'
          - 'c67.ne.cloud.epfl.ch:2379'
          - 'c68.ne.cloud.epfl.ch:2379'
          - 'c69.ne.cloud.epfl.ch:2379'
          - 'c70.ne.cloud.epfl.ch:2379'
          - 'c71.ne.cloud.epfl.ch:2379'
          - 'c72.ne.cloud.epfl.ch:2379'
          - 'c73.ne.cloud.epfl.ch:2379'
          - 'c74.ne.cloud.epfl.ch:2379'
          - 'c75.ne.cloud.epfl.ch:2379'
          - 'c76.ne.cloud.epfl.ch:2379'
          - 'c77.ne.cloud.epfl.ch:2379'
          - 'c78.ne.cloud.epfl.ch:2379'
          - 'c79.ne.cloud.epfl.ch:2379'
        labels:
          job: 'etcd2'
      - targets:
          - 'c01.ne.cloud.epfl.ch:8087'
          - 'c02.ne.cloud.epfl.ch:8087'
          - 'c03.ne.cloud.epfl.ch:8087'
          - 'c04.ne.cloud.epfl.ch:8087'
          - 'c05.ne.cloud.epfl.ch:8087'
          - 'c06.ne.cloud.epfl.ch:8087'
          - 'c07.ne.cloud.epfl.ch:8087'
          - 'c08.ne.cloud.epfl.ch:8087'
          - 'c09.ne.cloud.epfl.ch:8087'
          - 'c10.ne.cloud.epfl.ch:8087'
          - 'c11.ne.cloud.epfl.ch:8087'
          - 'c12.ne.cloud.epfl.ch:8087'
          - 'c13.ne.cloud.epfl.ch:8087'
          - 'c14.ne.cloud.epfl.ch:8087'
          - 'c15.ne.cloud.epfl.ch:8087'
          - 'c16.ne.cloud.epfl.ch:8087'
          - 'c17.ne.cloud.epfl.ch:8087'
          - 'c18.ne.cloud.epfl.ch:8087'
          - 'c19.ne.cloud.epfl.ch:8087'
          - 'c20.ne.cloud.epfl.ch:8087'
          - 'c21.ne.cloud.epfl.ch:8087'
          - 'c22.ne.cloud.epfl.ch:8087'
          - 'c23.ne.cloud.epfl.ch:8087'
          - 'c24.ne.cloud.epfl.ch:8087'
          - 'c25.ne.cloud.epfl.ch:8087'
          - 'c26.ne.cloud.epfl.ch:8087'
          - 'c27.ne.cloud.epfl.ch:8087'
          - 'c28.ne.cloud.epfl.ch:8087'
          - 'c29.ne.cloud.epfl.ch:8087'
          - 'c30.ne.cloud.epfl.ch:8087'
          - 'c31.ne.cloud.epfl.ch:8087'
          - 'c32.ne.cloud.epfl.ch:8087'
          - 'c33.ne.cloud.epfl.ch:8087'
          - 'c34.ne.cloud.epfl.ch:8087'
          - 'c35.ne.cloud.epfl.ch:8087'
          - 'c36.ne.cloud.epfl.ch:8087'
          - 'c37.ne.cloud.epfl.ch:8087'
          - 'c38.ne.cloud.epfl.ch:8087'
          - 'c39.ne.cloud.epfl.ch:8087'
          - 'c40.ne.cloud.epfl.ch:8087'
          - 'c41.ne.cloud.epfl.ch:8087'
          - 'c42.ne.cloud.epfl.ch:8087'
          - 'c43.ne.cloud.epfl.ch:8087'
          - 'c44.ne.cloud.epfl.ch:8087'
          - 'c45.ne.cloud.epfl.ch:8087'
          - 'c46.ne.cloud.epfl.ch:8087'
          - 'c47.ne.cloud.epfl.ch:8087'
          - 'c48.ne.cloud.epfl.ch:8087'
          - 'c49.ne.cloud.epfl.ch:8087'
          - 'c50.ne.cloud.epfl.ch:8087'
          - 'c51.ne.cloud.epfl.ch:8087'
          - 'c52.ne.cloud.epfl.ch:8087'
          - 'c53.ne.cloud.epfl.ch:8087'
          - 'c54.ne.cloud.epfl.ch:8087'
          - 'c55.ne.cloud.epfl.ch:8087'
          - 'c56.ne.cloud.epfl.ch:8087'
          - 'c57.ne.cloud.epfl.ch:8087'
          - 'c58.ne.cloud.epfl.ch:8087'
          - 'c59.ne.cloud.epfl.ch:8087'
          - 'c60.ne.cloud.epfl.ch:8087'
          - 'c61.ne.cloud.epfl.ch:8087'
          - 'c62.ne.cloud.epfl.ch:8087'
          - 'c63.ne.cloud.epfl.ch:8087'
          - 'c64.ne.cloud.epfl.ch:8087'
          - 'c65.ne.cloud.epfl.ch:8087'
          - 'c66.ne.cloud.epfl.ch:8087'
          - 'c67.ne.cloud.epfl.ch:8087'
          - 'c68.ne.cloud.epfl.ch:8087'
          - 'c69.ne.cloud.epfl.ch:8087'
          - 'c70.ne.cloud.epfl.ch:8087'
          - 'c71.ne.cloud.epfl.ch:8087'
          - 'c72.ne.cloud.epfl.ch:8087'
          - 'c73.ne.cloud.epfl.ch:8087'
          - 'c74.ne.cloud.epfl.ch:8087'
          - 'c75.ne.cloud.epfl.ch:8087'
          - 'c76.ne.cloud.epfl.ch:8087'
          - 'c77.ne.cloud.epfl.ch:8087'
          - 'c78.ne.cloud.epfl.ch:8087'
          - 'c79.ne.cloud.epfl.ch:8087'
        labels:
          job: 'cadvisor'

